using '../deploy-baseline.bicep'

param deploymentPrefix = 'AVD3'
param avdUseCustomNaming = false
param avdSessionHostLocation = 'eastus2'
param avdManagementPlaneLocation = 'eastus2'
param avdDeployMonitoring = false
param avdWorkloadSubsId = '7e30d173-52bf-4223-9827-cd0ea74e3e7f' // value needs to be provided
param avdEnterpriseAppObjectId = 'e67f9657-3392-476e-ad0c-db8a7fbb0317' // Value needs to be provided when enabling start VM on connect or scaling plans
param avdVmLocalUserName = 'avdadmin' // value needs to be provided
param avdVmLocalUserPassword = '!QAZ2wsx3edc!QAZ' // value needs to be provided
param avdIdentityServiceProvider = 'ADDS'
param createIntuneEnrollment = false
param securityPrincipalId = '2d744331-c049-4e36-adc5-98774408be5c'
param securityPrincipalName = 'github-actions-sp'
param identityDomainName = 'none' // value needs to be provided when using ADDS or EntraDS as identity service provider
param avdDomainJoinUserName = 'none'
param avdDomainJoinUserPassword = 'none'
param avdOuPath = ''
param avdHostPoolType = 'Personal'
param hostPoolPreferredAppGroupType = 'Desktop'
param avdPersonalAssignType = 'Automatic'
param avdHostPoolLoadBalancerType = 'none'
param hostPoolMaxSessions = 1
param avdStartVmOnConnect = true
param avdHostPoolRdpProperties = 'audiocapturemode:i:1;audiomode:i:0;drivestoredirect:s:;redirectclipboard:i:1;redirectcomports:i:1;redirectprinters:i:1;redirectsmartcards:i:1;screen mode id:i:2'
param avdDeployScalingPlan = true
param createAvdVnet = true
param existingVnetAvdSubnetResourceId = 'a4a3daca-31a8-4091-9233-a5d848ca0554'
param existingVnetPrivateEndpointSubnetResourceId = ''
param existingHubVnetResourceId = ''
param avdVnetworkAddressPrefixes = '10.10.0.0/22'
param vNetworkAvdSubnetAddressPrefix = '10.10.1.0/24'
param vNetworkPrivateEndpointSubnetAddressPrefix = '10.10.2.0/27'
param customDnsIps = '<<customDnsIp>>' // value needs to be provided when creating new AVD vNet and using ADDS or EntraDS identity service providers
param createPrivateDnsZones = false
param avdVnetPrivateDnsZoneFilesId = '<<PrivateDnsZoneFilesId>>' // Not a mandatory parameter
param avdVnetPrivateDnsZoneKeyvaultId = '<<PrivateDnsZoneKeyvaultId>>' // Not a mandatory parameter
param vNetworkGatewayOnHub = false
param createAvdFslogixDeployment = false
param createMsixDeployment = false
param fslogixFileShareQuotaSize = 0
param msixFileShareQuotaSize = 0
param avdDeploySessionHosts = true
param avdDeploySessionHostsCount = 1
param avdSessionHostCountIndex = 0
param availabilityZonesCompute = true
param zoneRedundantStorage = false
param fslogixStoragePerformance = 'Premium'
param msixStoragePerformance = 'Premium'
param avdSessionHostsSize = 'Standard_D2s_v3'
param avdSessionHostDiskType = 'Premium_LRS'
param avdOsImage = 'win11_23h2'
param managementVmOsImage = 'winServer_2022_Datacenter_smalldisk_g2'
param securityType = 'TrustedLaunch'
param secureBootEnabled = true
param vTpmEnabled = true
param useSharedImage = false
param avdImageTemplateDefinitionId = '/subscriptions/7e30d173-52bf-4223-9827-cd0ea74e3e7f/resourceGroups/DefaultResourceGroup-CID/providers/Microsoft.Compute/galleries/avdimage3/images/image3/versions/0.0.1'
param storageOuPath = ''
param createResourceTags = false
param deployAlaWorkspace = true
param alaExistingWorkspaceResourceId = ''
param avdAlaWorkspaceDataRetention = 90
param enableAcceleratedNetworking = true
param diskEncryptionKeyExpirationInDays = 60
param diskZeroTrust = false
param deployGpuPolicies = false
param deployVmssFlex = true
param deployAntiMalwareExt = true
